name: Daily Post Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai feedparser requests

      - name: Run Daily Post Generator
        run: python ./.github/workflows/daily_post_generator.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push new post
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add new daily automated post"
          branch: main
          file_pattern: blog/*.html blog-index.json