name: Daily Post Generator

on:
  # This allows you to run the action manually from the Actions tab on GitHub.
  workflow_dispatch:
  
  # This sets the schedule. It will run automatically every day at 8:00 AM IST (2:30 AM UTC).
  schedule:
    - cron: '30 2 * * *'

# This new block grants the necessary permission for the action to push code.
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the Python programming language environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installs the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai feedparser requests

      # 4. Runs our Python script to generate the new post
      - name: Run Daily Post Generator
        run: python ./.github/workflows/daily_post_generator.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # 5. Automatically commits the new blog post files to your repository
      - name: Commit and push new post
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add new daily automated post"
          branch: main
          file_pattern: blog/*.html blog-index.json